baseURL = 'https://jordismit.com'
copyright = "Jordi Smit - All rights reserved"
enableRobotsTXT = true
languageCode = 'en-us'
summaryLength = 20
title = 'J0rd1Smit'

[[menu.main]]
identifier = "Blog"
name = "Blog"
url = "/blog"
weight = 100

[[menu.main]]
identifier = "til"
name = "TIL"
url = "/til"
weight = 200

[[menu.main]]
identifier = "cheat-sheets"
name = "Cheat-sheets"
url = "/cheat-sheets"
weight = 300

[[menu.main]]
identifier = "about"
name = "About Me"
url = "/about"
weight = 400

[params]

[params.author]
firstName = 'Jordi'
jobTitle = 'Machine Learning Engineer'
lastName = 'Smit'
thumbnail = "media/images/author.jpg"

[params.index]
picture = "/images/author.jpg"
subtitle = "Machine Learning Engineer"
title = "Jordi Smit"

[params.social]
github = "j0rd1smit"
linkedin = "ðŸ‘‹jordi-smit-8778b51b4"
twitter = "j0rd1smit"

[permalinks]
blog = '/blog/:title'
cheat-sheets = '/cheat-sheets/:title'
til = '/til/:title'
